---
- name: Identify gitea users
  ansible.builtin.command: su - {{ gitea_user }} -c '{{ gitea_full_executable_path }} -c {{ gitea_configuration_path }}/gitea.ini admin user list'
  become: true
  register: _giteusers
  changed_when: false

- name: Use gitea cli to create user
  become: true
  ansible.builtin.command: |
    su - {{ gitea_user }} -c
    '{{ gitea_full_executable_path }} -c {{ gitea_configuration_path }}/gitea.ini
    admin user create --username "{{ item.name }}"
    --password "{{ item.password }}" --email "{{ item.email }}"
    --must-change-password={{ item.must_change_password }} --admin={{ item.admin }}'
  register: _gitearesult
  failed_when:
    - '"successfully created" not in gitearesult.stdout'
  changed_when:
    - '"successfully created!" in gitearesult.stdout'
  when: "_giteusers is defined and item.name in _giteusers"
  loop: "{{ gitea_users }}"
